# Sample entrypoint configuration when using ACME
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "kyrianae@gmail.com"
storage = "acme.json"
entryPoint = "https"
#caServer = "https://acme-staging.api.letsencrypt.org/directory"
acmeLogging = true
onHostRule = true

[acme.tlsChallenge]

[docker]
endpoint = "unix:///var/run/docker.sock"

domain = "jorlando.fr"

watch = true

exposedbydefault = false

[api]
  dashboard = true

logLevel = "INFO"

[metrics]
  [metrics.influxdb]
    address = "http://influxdb:8086"
    database = "monitoring"
    protocol = "http"
